package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Autorization HH")
    void generatedTest() {
        step("Open 'https://hh.ru/account/login?backurl=%2Fapplicant%2Fresumes%2Fnew'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set username 'anet_ta@mail.ru'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set password 'Anna140184'", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify successfull  autorization as 'Анна'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://hh.ru/account/login?backurl=%2Fapplicant%2Fresumes%2Fnew'", () ->
            open("https://hh.ru/account/login?backurl=%2Fapplicant%2Fresumes%2Fnew"));

        step("Page title should have text 'Вход в личный кабинет'", () -> {
            String expectedTitle = "Вход в личный кабинет";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://hh.ru/account/login?backurl=%2Fapplicant%2Fresumes%2Fnew'", () ->
            open("https://hh.ru/account/login?backurl=%2Fapplicant%2Fresumes%2Fnew"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}